In [1]:
import torch

# Scalar

In [2]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [3]:
scalar2 = torch.tensor([3.])    
print(scalar2)

tensor([3.])


In [4]:
# 스칼라값 간의 사칙 연산
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [5]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [6]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [7]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


In [8]:
# 스칼라값의 사칙연산을 torch 모듈에 내장된 메서드를 이용해 계산 가능
torch.add(scalar1, scalar2)

tensor([4.])

In [9]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [10]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [11]:
torch.div(scalar1, scalar2)

tensor([0.3333])

# Vector

In [12]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [13]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


In [14]:
# 벡터 간 사칙연산, 곱셈과 나눗셈은 각 요소별로 연산(element-wise)
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [15]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [16]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [17]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [18]:
# 벡터 값 간 사칙연산 역시 torch 모듈에 내장된 메서드를 이용해 계산 가능
torch.add(vector1, vector2)

tensor([5., 7., 9.])

In [19]:
torch.sub(vector1, vector2)

tensor([-3., -3., -3.])

In [20]:
torch.mul(vector1, vector2)

tensor([ 4., 10., 18.])

In [21]:
torch.div(vector1, vector2)

tensor([0.2500, 0.4000, 0.5000])

In [22]:
torch.dot(vector1, vector2)

tensor(32.)

# Matrix

In [23]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


In [25]:
# 행렬 간 사칙연산 수행, 스칼라 벡터 사칙연산과 동일한 방식
sum_matrix = matrix1 + matrix2
print(sum_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [26]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [27]:
mul_matrix = matrix1 * matrix2
print(mul_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [28]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [29]:
# 행렬 값 간 사칙연산 역신 troch 모듈에 내장된 메서드 사용 가능
# 행렬 값 간 사칙연산 역시 벡터 연산처럼 각 요소별로 계산(element-wise)
torch.add(matrix1, matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [30]:
torch.sub(matrix1, matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [31]:
# 행렬 값 간 각 요소별 곱셈
torch.mul(matrix1, matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [32]:
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [33]:
# 행렬 곱 연산
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

# Tensor

In [34]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [35]:
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [36]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [37]:
sub_tensor = tensor1 - tensor2
print(sub_tensor)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [38]:
mul_tensor = tensor1 * tensor2
print(mul_tensor)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


In [39]:
div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [40]:
# 텐서 간 텐서곱 (두 텐서의 모양이 모두 [2 x 2 x 2]이기 때문에 행렬 곱 연산 가능)
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

In [41]:
torch.add(tensor1, tensor2)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [42]:
torch.sub(tensor1, tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [43]:
torch.mul(tensor1, tensor2)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

In [44]:
torch.div(tensor1, tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

In [45]:
tensor1

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [46]:
tensor2

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])

In [47]:
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

In [48]:
import torch

if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

BATCH_SIZE = 64 # 딥러닝 모델에서 파라미터를 업데이트할 때 계산되는 데이터의 개수
                # BATCH_SIZE 수만큼 데이터를 이용해 Output을 계산하고, BATCH_SIZE 수만큼 출력된 결괏값에 오찻값 계산
                # BATCH_SIZE 수만큼 계산된 오찻값을 평균해 Back Propagation을 적용하고 이를 바탕으로 파라미터 업데이트
INPUT_SIZE = 1000 # 딥러닝 모델에서 Input의 크기이자 입력층의 노드 수
HIDDEN_SIZE = 100 # 딥러닝 모델에서 Input을 다수의 파라미터를 이용해 계산한 결과에 한 번 더 계산되는 파라미터 수
OUTPUT_SIZE = 10 # 딥러닝 모델에서 최종으로 출력되는 값의 벡터의 크기
                 # 최종으로 비교하고자 하는 레이블의 크기와 동일하게 설정

# (64, 1000)의 Input이 (1000, 100) 크기의 행렬과 행렬곱을 계산

x = torch.randn(BATCH_SIZE, 
                INPUT_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = False)  
# (64, 1000) 모양의 데이터가 생성, 데이터의 형태는 float
# Input으로 이용되기 때문에, Gradient를 업데이트 할 필요가 없어, requires_grad = False 설정
y = torch.randn(BATCH_SIZE, 
                OUTPUT_SIZE, 
                device = DEVICE,
                dtype = torch.float, 
                requires_grad = False)  
# 위와 동일
w1 = torch.randn(INPUT_SIZE, 
                 HIDDEN_SIZE, 
                 device = DEVICE, 
                 dtype = torch.float,
                 requires_grad = True)  
# 업데이트할 파라미터 값, W1은 Input의 크기가 1,000이며 이와 행렬 곱을 하기 위해 다음 행의 값이 1,000이어야 함
# 행렬 곱을 이용해 100 크기의 데이터를 생성하기 위해 (1000, 100) 크기의 데이터 생성
w2 = torch.randn(HIDDEN_SIZE,
                 OUTPUT_SIZE, 
                 device = DEVICE,
                 dtype = torch.float,
                 requires_grad = True)  
# W2는 W1과 x를 행렬 곱한 결과에 계산할 수 있는 데이터여야 함, W1과 x를 행렬 곱한 결과는 (1,100)이며 (100, 10) 행렬을 통해 Output을 계산하기 위해 W2 모양 설정

# randn을 통해 평균이 0, 표준편차가 1인 정규분포에서 샘플링

learning_rate = 1e-6                                           
for t in range(1, 501): # 500번 반복해 파라미터 값 업데이트                                      
    y_pred = x.mm(w1).clamp(min = 0).mm(w2) # 딥러닝 모델의 결과값(예측값) , Input과 W1의 행렬 곱을 이용해 나온 결괏값 계산
                                            # clamp method를 통해 비선형 함수를 적용, clamp는 ReLU와 같은 역할
                                            # clamp를 이용해 계산된 결과와 W2를 이용해 행렬 곱을 한 번 더 계산하며 이 결과가 Output을 의미

    loss = (y_pred - y).pow(2).sum() # 예측값과 실제 레이블 값을 비교해 오차를 계산
                                     # 오차를 계산한 뒤, pow 함수를 이용해 제곱을 취함 (지수를 취하는 기본 메서드) 이후 제곱합 계산
    if t % 100 == 0: # 반복 횟수가 100으로 나눠 떨어질 때, 현재 진행 중인 반복문 횟수와 Loss값 설정
        print("Iteration: ", t, "\t", "Loss: ", loss.item()) 
    loss.backward() # 계산된 Loss 값에 대해 backward() 메서드를 이용해 각 파라미터 값에 대해 기울기를 계산한 뒤 역전파를 진행                                          

    with torch.no_grad(): # 각 파라미터 값에 대해 기울기를 계산한 결과를 이용해 파라미터 값을 업데이트할 때는 해당 시점의 기울기 값을 고정한 뒤 업데이트                                     
        w1 -= learning_rate * w1.grad # 기울기 값을 고정한 상태에서 W1의 기울기 값과 학습률을 곱한 결과값을 기존 W1 값으로 지종
                                      # 음수를 이용하는 이유는 Loss 값이 최소로 계싼될 수 있는 파라미터 값을 찾기 위해, 기울기 값에 대한 반대방향으로 계산
        w2 -= learning_rate * w2.grad # 위와 동일                         

        w1.grad.zero_()                                      
        w2.grad.zero_()
        # 위 과정을 통해 각 파라미터 값을 업데이트 했다면, 각 파라미터 값의 기울기를 초기화해 다음 반복문이 진행되도록 기울기를 0으로 설정

Iteration:  100 	 Loss:  527.76318359375
Iteration:  200 	 Loss:  3.209841728210449
Iteration:  300 	 Loss:  0.03574322536587715
Iteration:  400 	 Loss:  0.0007254641968756914
Iteration:  500 	 Loss:  8.230483217630535e-05


In [49]:
# Iteration:  100 	 Loss:  976.0719604492188
# Iteration:  200 	 Loss:  5.061180114746094
# Iteration:  300 	 Loss:  0.04102771729230881
# Iteration:  400 	 Loss:  0.0006718397489748895
# Iteration:  500 	 Loss:  6.94335249136202e-05